version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: accountable_holo_db
    restart: always
    environment:
      POSTGRES_USER: nelson
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accountableholodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
