Website = "https://github.com/nelsonmarro/accountable-holo"

[Details]
  Icon = "../../assets/accounts_tab_icon_dark.png"
  Name = "Accountable Holo"
  ID = "51af2ee4-c61c-4608-a3f1-d8576343af14"
  Version = "1.0.0"
  Build = 8
